/**
 * GENERATED by scripts/mine-plays.ts --write. Do not edit by hand.
 *
 * Empty until the miner has run. An empty list is the correct starting state:
 * formatMinedPlaysForBriefing returns "" and the briefing is exactly what it
 * was, rather than carrying a heading with nothing under it.
 */

export type MinedPlay = {
  kind: string;
  quote: string;
  doing: string;
  speaker: string;
  rep: string;
  account: string;
  stage: string | null;
  callDate: string;
  precededAdvance: boolean;
  nextMeetingInAWeek: boolean;
};

export const MINED_PLAYS: MinedPlay[] = [];
